server:
  port: ${SERVER_PORT:8080}
## Spring boot configs
spring:
  application:
    name: ${SPRING_APPLICATION_NAME:Tele-Tracking-System}
# Datasource configuration
  datasource:
    url:               ${SPRING_DATASOURCE_URL}${SPRING_DATASOURCE_DB}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    username:          ${SPRING_DATASOURCE_USERNAME}
    password:          ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
  sql.init.mode: never
  # Mongodb
  data:
    mongodb:
      uri:      ${SPRING_DATA_MONGODB_URI}
      database: ${SPRING_DATA_MONGODB_DATABASE}
      authentication-database: admin
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db
    placeholder-replacement: false

#Prometheus
management:
  server.port: ${SERVER_PORT:8080}
  metrics:
    export:
      prometheus:
        enabled: ${MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED}
    tags:
      environment: ${MANAGEMENT_METRICS_TAGS_ENVIRONMENT}
      service_id: ${MANAGEMENT_METRICS_TAGS_SERVICE_ID}

#Appication config
tracking:
  number:
    refill:
      threshold: ${TRACKING_NUMBER_REFILL_THRESHOLD}