apiVersion: v1
kind: Service
metadata:
  name: tracking-service
  labels:
    app: tracking-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
spec:
  selector:
    app: tracking-service
  ports:
    - port: 8080
      targetPort: 8080